Configure model_name from timm and folder_name of any dataset
Entry point: python main.py
Models tested:
1. [convnextv2_base.fcmae_ft_in22k_in1k_384](https://huggingface.co/timm/convnextv2_base.fcmae_ft_in22k_in1k_384)
2. [vit_base_patch16_rope_mixed_ape_224.naver_in1k](https://huggingface.co/timm/vit_base_patch16_rope_mixed_ape_224.naver_in1k)
3. [vit_pe_core_large_patch14_336.fb](https://huggingface.co/timm/vit_pe_core_large_patch14_336.fb)
4. [vit_base_r50_s16_224.orig_in21k](https://huggingface.co/timm/vit_base_r50_s16_224.orig_in21k)
5. [vit_pe_spatial_large_patch14_448.fb](https://huggingface.co/timm/vit_pe_spatial_large_patch14_448.fb)
6. [vit_base_patch14_dinov2.lvd142m](https://huggingface.co/timm/vit_base_patch14_dinov2.lvd142m)
7. [MahmoodLab/uni](https://huggingface.co/MahmoodLab/UNI)

errors/<data_name>: contains error matrix images for different models.